;;; text-input-corpus-test.el --- 10k public-author replay -*- lexical-binding: t; -*-

;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Commentary:

;; Replays the seed-20260828 corpus generated by
;; `generate-text-input-corpus.py' through the public Elisp constructor.  The
;; receiver may accept unknown fallback enums that this strict author rejects;
;; every other author-valid row must serialize canonically to the shared node.

;;; Code:

(require 'ert)
(require 'jetpacs-widgets)

(defconst jetpacs-text-input-corpus--members
  '((:value . :value)
    (:hint . :hint)
    (:label . :label)
    (:on_change . :on-change)
    (:on_submit . :on-submit)
    (:single_line . :single-line)
    (:min_lines . :min-lines)
    (:max_lines . :max-lines)
    (:monospace . :monospace)
    (:syntax . :syntax)
    (:password . :password)
    (:keyboard . :keyboard)
    (:autofocus . :autofocus)
    (:clear_on_submit . :clear-on-submit)
    (:variant . :variant)
    (:is_error . :is-error)
    (:supporting_text . :supporting-text)
    (:prefix . :prefix)
    (:suffix . :suffix)
    (:leading_icon . :leading-icon)
    (:trailing_icon . :trailing-icon)
    (:max_length . :max-length)
    (:selection . :selection)
    (:hide_keyboard_on_submit . :hide-keyboard-on-submit)
    (:content_padding . :content-padding)
    (:mask . :mask)
    (:filter . :filter)
    (:enabled . :enabled))
  "Wire keyword to public `jetpacs-text-input' keyword mappings.")

(defun jetpacs-text-input-corpus--build (node)
  "Build the text-input plist represented by parsed corpus NODE."
  (let ((id (plist-get node :id)) args)
    (dolist (mapping jetpacs-text-input-corpus--members)
      (when (plist-member node (car mapping))
        (let ((value (plist-get node (car mapping))))
          ;; The public constructor accepts a list seed and emits a vector;
          ;; JSON parsing naturally supplies the wire vector.
          (when (and (eq (car mapping) :selection) (vectorp value))
            (setq value (append value nil)))
          (push (cdr mapping) args)
          (push value args))))
    (apply #'jetpacs-text-input id (nreverse args))))

(defun jetpacs-text-input-corpus--utf8-bytes (string)
  "Return STRING as an unibyte UTF-8 byte sequence."
  (if (multibyte-string-p string)
      (encode-coding-string string 'utf-8)
    string))

(ert-deftest jetpacs-text-input-corpus/public-author-replay ()
  "Replay all 10,000 deterministic cases through the public constructor."
  (let ((path (getenv "JETPACS_TEXT_INPUT_CORPUS"))
        (count 0)
        (families (make-hash-table :test #'eql)))
    (should (and path (file-readable-p path)))
    (with-temp-buffer
      (insert-file-contents path)
      (goto-char (point-min))
      (while (not (eobp))
        (let* ((line (buffer-substring-no-properties
                      (line-beginning-position) (line-end-position)))
               (row (json-parse-string
                     line :object-type 'plist :array-type 'array
                     :null-object nil :false-object :json-false))
               (valid (eq (plist-get row :author_valid) t))
               (node (plist-get row :node))
               built failure)
          (condition-case error-data
              (setq built (jetpacs-text-input-corpus--build node))
            (error (setq failure error-data)))
          (if valid
              (progn
                (should-not failure)
                (should
                 (equal
                  (jetpacs-text-input-corpus--utf8-bytes
                   (jetpacs-node->canonical-json built))
                  (jetpacs-text-input-corpus--utf8-bytes
                   (plist-get row :canonical)))))
            (should failure))
          (puthash (plist-get row :family) t families)
          (setq count (1+ count)))
        (forward-line 1)))
    (should (= count 10000))
    (should (= (hash-table-count families) 32))))

(provide 'text-input-corpus-test)
;;; text-input-corpus-test.el ends here
