#!/usr/bin/env python3
"""Generate MODIFIERS-REFERENCE.org from contract.json + Attributes.kt.

The attribute list comes from the sibling `ebp/contract.json`'s
`universal_node_attributes` (the authority — SPEC §16.5); the type
column from `field_types` where the contract projects one; the handler
column is the actual line(s) in the renderer's Attributes.kt that read
the member, located by grep at generation time so the reference and the
code cannot drift apart silently.

Regenerate after any change to contract.json or Attributes.kt:

    python3 docs/material3/lookup-tables/generate-modifier-table.py

Content below the sentinel line is hand-authored and preserved verbatim.
"""

import json
import os
import re
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, "..", "..", ".."))
REPOSITORIES_ROOT = os.environ.get("JETPACS_REPOSITORIES_ROOT") or next(
    (os.path.abspath(os.path.join(ROOT, *parts)) for parts in [("..",), ("..", "..")]
     if os.path.isfile(os.path.join(ROOT, *parts, "ebp", "SPEC.md"))), None)
if not REPOSITORIES_ROOT and not os.environ.get("EBP_SPEC_DIR"):
    raise SystemExit("Set EBP_SPEC_DIR or JETPACS_REPOSITORIES_ROOT")
EBP_ROOT = os.environ.get("EBP_SPEC_DIR") or os.path.join(REPOSITORIES_ROOT, "ebp")
OUT = os.path.join(HERE, "MODIFIERS-REFERENCE.org")
ATTRS_KT = os.path.join(
    ROOT, "companion/renderer/material3/src/main/kotlin/com/calebc42/jetpacs/"
    "material3/Attributes.kt")
SENTINEL = ("# >>> HAND-AUTHORED BELOW — proposals / ideation; "
            "not implemented; preserved verbatim by the generator")


def main():
    contract = json.load(open(os.path.join(EBP_ROOT, "contract.json")))
    attrs = contract["universal_node_attributes"]
    ftypes = contract.get("field_types", {})
    src = open(ATTRS_KT, encoding="utf-8").read().splitlines()

    tail = ""
    if os.path.exists(OUT):
        old = open(OUT, encoding="utf-8").read()
        if SENTINEL in old:
            tail = old[old.index(SENTINEL):]

    w = []
    w.append("# -*- mode: org; coding: utf-8 -*-")
    w.append("#+TITLE: Jetpacs Modifier Reference")
    w.append("#+AUTHOR: GENERATED by generate-modifier-table.py — do not edit above the sentinel")
    w.append("#+STARTUP: showall")
    w.append("#+OPTIONS: ^:nil")
    w.append("")
    w.append("* Jetpacs Modifier Reference")
    w.append("")
    w.append("GENERATED from =ebp/contract.json='s =universal_node_attributes=")
    w.append("(SPEC §16.5) and located in the renderer's =Attributes.kt= by grep")
    w.append("at generation time.  =contract.json= is authoritative; this table")
    w.append("is orientation (SPEC §24.4).  Line numbers are valid for the")
    w.append("commit this file was generated at and refresh on regeneration.")
    w.append("")
    w.append(f"** Universal node attributes ({len(attrs)})")
    w.append("")
    w.append("| Attribute | Contract type | Read in Attributes.kt |")
    w.append("|---|---|---|")
    missing = []
    for a in attrs:
        t = ftypes.get(a) or "—"
        hits = [str(i + 1) for i, line in enumerate(src)
                if f'"{a}"' in line]
        where = ("Attributes.kt:" + ",".join(hits[:4])) if hits else "not found"
        if not hits:
            missing.append(a)
        w.append(f"| ={a}= | ={t}=" .replace("=—=", "—") + f" | {where} |")
    w.append("")
    if missing:
        w.append("Attributes with no direct read in Attributes.kt (handled in a")
        w.append("node renderer or the diffing layer, not the modifier chain): "
                 + ", ".join(f"={a}=" for a in missing) + ".")
        w.append("")
    body = "\n".join(w)
    body += ("\n" + tail) if tail else "\n"
    open(OUT, "w", encoding="utf-8").write(body)
    print(f"wrote {OUT}; {len(attrs)} attributes, "
          f"{len(missing)} without a direct Attributes.kt read")


if __name__ == "__main__":
    main()
