// SPDX-License-Identifier: GPL-3.0-or-later
// GENERATED from ebp/contract.json (format 9,
// spec 3.1.0-draft) by tools/gen-vocabulary.py — DO NOT EDIT.
// VocabularyDriftTest re-reads the contract and fails on any disagreement.
package com.calebc42.ebp.wire

data class NodeRow(val required: Set<String>, val optional: Set<String>)
data class ActionRow(val required: Set<String>, val optional: Set<String>)
/** Required, optional, and typed members for one contract-projected object. */
data class SemanticObjectRow(
    val required: Set<String>,
    val optional: Set<String>,
    val fieldTypes: Map<String, String>,
)

/** Contract-projected node defaults; no receiver may invent a role override. */
data class DefaultSemanticRow(
    val role: String? = null,
    val roleConditionMember: String? = null,
    val headingLevel: Int? = null,
    val enabledMember: String? = null,
    val readOnlyMember: String? = null,
    val readOnlyInverted: Boolean = false,
    val checkedMember: String? = null,
    val checkedDefault: Boolean? = null,
    val toggleStateMember: String? = null,
    val selectedMember: String? = null,
    val selectedDefault: Boolean? = null,
    val selectionMember: String? = null,
    val selectionDefaultIndex: Int? = null,
    val expandedMember: String? = null,
    val expandedInverted: Boolean = false,
    val progressValueMember: String? = null,
    val progressMinMember: String? = null,
    val progressMaxMember: String? = null,
    val progressMin: Double? = null,
    val progressMax: Double? = null,
    val indeterminateWhenValueAbsent: Boolean = false,
    val progressValueDefaultsToMin: Boolean = false,
    val customActionsFrom: List<String> = emptyList(),
)

/** Contract-projected authored selection seed for a text input. */
data class TextInputSelectionContract(
    val type: String,
    val unit: String,
    val minimum: Long,
    val order: String,
    val upperBound: String,
    val lifecycle: String,
    val whenRetainedDraftWins: String,
)

/** Contract-projected maximum-length rule for a text input. */
data class TextInputMaxLengthContract(
    val type: String,
    val unit: String,
    val behavior: String,
    val authoredValueMustFit: Boolean,
    val retainedDraftMustFit: Boolean,
)

/** Contract-projected mask grammar for a text input. */
data class TextInputMaskContract(
    val slot: String,
    val minimumSlots: Int,
    val unit: String,
    val overflow: String,
    val incompatibleWith: Set<String>,
)

/** Contract-projected interior-padding rule for a text input. */
data class TextInputPaddingContract(
    val type: String,
    val appliesTo: String,
)

/** Complete generated §17.4 constraint envelope for `text_input`. */
data class TextInputContract(
    val selection: TextInputSelectionContract,
    val maxLength: TextInputMaxLengthContract,
    val transformOrder: List<String>,
    val filterCharacterSets: Map<String, String>,
    val filterUnknown: String,
    val filterAuthoredValueMustMatch: Boolean,
    val filterRetainedDraftMustMatch: Boolean,
    val mask: TextInputMaskContract,
    val contentPadding: TextInputPaddingContract,
    val variantDefault: String,
    val variantUnknown: String,
    val hideKeyboardOnSubmitRequires: String,
    val errorDescriptionPrecedence: List<String>,
    val logicalValueExcludes: List<String>,
)

const val CONTRACT_FORMAT = 9
const val PROTOCOL_VERSION = 3
const val SPEC_VERSION = "3.1.0-draft"

val CORE_NODE_SET: Set<String> = setOf("text", "row", "column", "box", "spacer", "divider", "button", "text_input")

val UNIVERSAL_NODE_ATTRIBUTES: Set<String> = setOf("key", "id", "scroll_here", "padding", "pad", "width", "height", "min_width", "max_width", "min_height", "max_height", "fill_fraction", "aspect_ratio", "weight", "bg", "corner", "border", "alpha", "clip", "align_self", "semantics")

const val MAX_SEMANTIC_ACTIONS_PER_NODE = 8

val SEMANTICS_SCHEMA = SemanticObjectRow(
    required = setOf(),
    optional = setOf("name", "description", "state_description", "error", "pane_title", "heading_level", "live_region", "collection", "collection_item", "traversal_group", "traversal_index", "actions"),
    fieldTypes = mapOf("name" to "non-empty-plain-string", "description" to "non-empty-plain-string", "state_description" to "non-empty-plain-string", "error" to "non-empty-plain-string", "pane_title" to "non-empty-plain-string", "heading_level" to "integer-1-6", "live_region" to "live-region-enum", "collection" to "semantic-collection-object", "collection_item" to "semantic-collection-item-object", "traversal_group" to "boolean", "traversal_index" to "finite-number", "actions" to "semantic-action-array"),
)

val SEMANTIC_OBJECT_SCHEMA: Map<String, SemanticObjectRow> = mapOf(
    "collection" to SemanticObjectRow(setOf("row_count", "column_count"), setOf(), mapOf("row_count" to "non-negative-integer", "column_count" to "positive-integer")),
    "collection_item" to SemanticObjectRow(setOf("row_index", "row_span", "column_index", "column_span"), setOf(), mapOf("row_index" to "non-negative-integer", "row_span" to "positive-integer", "column_index" to "non-negative-integer", "column_span" to "positive-integer")),
    "action" to SemanticObjectRow(setOf("label", "on_action"), setOf(), mapOf("label" to "non-empty-plain-string", "on_action" to "action-descriptor")),
)

val SEMANTIC_LIVE_REGIONS: Set<String> = setOf("polite", "assertive")
val SEMANTIC_ROLES: Set<String> = setOf("button", "image", "text_input", "checkbox", "switch", "selection_group", "tab_group", "dropdown", "slider", "progress")
val ACCESSIBLE_NAME_PRECEDENCE: List<String> = listOf(
    "semantics.name", "content_description", "label", "icon", "t", "node"
)

val DEFAULT_NODE_SEMANTICS: Map<String, DefaultSemanticRow> = mapOf(
    "section_header" to DefaultSemanticRow(headingLevel = 2),
    "progress" to DefaultSemanticRow(role = "progress", progressValueMember = "value", indeterminateWhenValueAbsent = true, progressMin = 0.0, progressMax = 1.0),
    "image" to DefaultSemanticRow(role = "image"),
    "button" to DefaultSemanticRow(role = "button", enabledMember = "enabled", checkedMember = "checked"),
    "icon_button" to DefaultSemanticRow(role = "button", enabledMember = "enabled", checkedMember = "checked"),
    "chip" to DefaultSemanticRow(role = "button", roleConditionMember = "on_tap", enabledMember = "enabled", selectedMember = "selected", selectedDefault = false),
    "empty_state" to DefaultSemanticRow(role = "button", roleConditionMember = "on_tap"),
    "date_button" to DefaultSemanticRow(role = "button", enabledMember = "enabled"),
    "time_button" to DefaultSemanticRow(role = "button", enabledMember = "enabled"),
    "text_input" to DefaultSemanticRow(role = "text_input", enabledMember = "enabled"),
    "editor" to DefaultSemanticRow(role = "text_input", enabledMember = "enabled", readOnlyMember = "read_only"),
    "search_bar" to DefaultSemanticRow(role = "text_input", enabledMember = "enabled"),
    "dropdown" to DefaultSemanticRow(role = "dropdown", enabledMember = "enabled", readOnlyMember = "editable", readOnlyInverted = true),
    "checkbox" to DefaultSemanticRow(role = "checkbox", enabledMember = "enabled", checkedMember = "checked", toggleStateMember = "state", checkedDefault = false),
    "switch" to DefaultSemanticRow(role = "switch", enabledMember = "enabled", checkedMember = "checked", checkedDefault = false),
    "enum_list" to DefaultSemanticRow(role = "selection_group", enabledMember = "enabled", selectionMember = "value"),
    "tabs" to DefaultSemanticRow(role = "tab_group", selectionMember = "initial", selectionDefaultIndex = 0),
    "segmented_button" to DefaultSemanticRow(role = "tab_group", enabledMember = "enabled", selectionMember = "value"),
    "slider" to DefaultSemanticRow(role = "slider", enabledMember = "enabled", progressValueMember = "value", progressMinMember = "min", progressMaxMember = "max", progressValueDefaultsToMin = true, progressMin = 0.0, progressMax = 1.0),
    "card" to DefaultSemanticRow(role = "button", roleConditionMember = "on_tap", customActionsFrom = listOf("swipe_start", "swipe_end")),
    "collapsible" to DefaultSemanticRow(expandedMember = "collapsed", expandedInverted = true, customActionsFrom = listOf("swipe_start", "swipe_end")),
)

/** Contract-projected enum vocabulary; senders reject unknown authored values. */
val ENUMS: Map<String, Set<String>> = mapOf(
    "text.style" to setOf("body", "title", "headline", "caption", "label", "mono"),
    "rich_text.style" to setOf("body", "title", "headline", "caption", "label", "mono"),
    "progress.variant" to setOf("circular", "linear", "linear_wavy", "circular_wavy", "loading", "contained_loading"),
    "button.variant" to setOf("filled", "tonal", "elevated", "outlined", "text"),
    "image.content_scale" to setOf("fit", "crop", "fill"),
    "row.align" to setOf("top", "center", "bottom", "baseline"),
    "column.align" to setOf("start", "center", "end"),
    "flow_row.align" to setOf("top", "center", "bottom"),
    "arrange" to setOf("start", "center", "end", "space_between", "space_around", "space_evenly"),
    "box.alignment" to setOf("top_start", "top_center", "top_end", "center_start", "center", "center_end", "bottom_start", "bottom_center", "bottom_end"),
    "surface.shape" to setOf("rounded", "rounded_small", "circle", "square", "slanted", "arch", "fan", "arrow", "semi_circle", "oval", "pill", "triangle", "diamond", "clam_shell", "pentagon", "gem", "sunny", "very_sunny", "cookie_4_sided", "cookie_6_sided", "cookie_7_sided", "cookie_9_sided", "cookie_12_sided", "ghostish", "clover_4_leaf", "clover_8_leaf", "burst", "soft_burst", "boom", "soft_boom", "flower", "puffy", "puffy_diamond", "pixel_circle", "pixel_triangle", "bun", "heart"),
    "chart.kind" to setOf("line", "bar", "area", "sparkline"),
    "canvas.op" to setOf("line", "rect", "circle", "path", "text"),
    "text_input.keyboard" to setOf("text", "number", "decimal", "email", "phone", "uri"),
    "align_self" to setOf("start", "center", "end", "stretch"),
    "dialog.style" to setOf("dialog", "sheet", "sheet_full"),
    "notification.priority" to setOf("min", "low", "default", "high", "max"),
    "diagnostic.severity" to setOf("error", "warning", "info", "hint"),
    "toolbar.placement" to setOf("cursor", "line-start", "block"),
    "button.size" to setOf("xsmall", "small", "medium", "large", "xlarge"),
    "button.shape" to setOf("round", "square"),
    "icon_button.variant" to setOf("filled", "tonal", "outlined"),
    "card.variant" to setOf("filled", "elevated", "outlined"),
    "chip.variant" to setOf("flat", "elevated", "input"),
    "assist_chip.variant" to setOf("flat", "elevated", "suggestion", "elevated_suggestion"),
    "text_input.variant" to setOf("outlined", "filled"),
    "slider.track" to setOf("default", "centered"),
    "slider.orientation" to setOf("horizontal", "vertical"),
    "checkbox.state" to setOf("off", "on", "indeterminate"),
    "text_input.filter" to setOf("digits", "alnum"),
    "menu.initial_scroll" to setOf("start", "end"),
    "date_button.mode" to setOf("calendar", "input"),
    "time_button.display_mode" to setOf("picker", "input", "switchable"),
    "tooltip.position" to setOf("above", "below", "left", "right", "start", "end"),
    "icon_button.size" to setOf("xsmall", "small", "medium", "large"),
    "icon_button.shape" to setOf("round", "square"),
    "icon_button.width_mode" to setOf("narrow", "uniform", "wide"),
    "split_button.variant" to setOf("filled", "tonal", "elevated", "outlined"),
    "split_button.size" to setOf("xsmall", "small", "medium", "large", "xlarge"),
    "scaffold.top_bar_style" to setOf("small", "center", "medium", "large", "medium_flexible", "large_flexible", "two_rows"),
    "scaffold.scroll_behavior" to setOf("pinned", "enter_always", "exit_until_collapsed"),
    "scaffold.refresh_indicator" to setOf("default", "loading", "none"),
    "scaffold.snackbar_duration" to setOf("short", "long", "indefinite"),
    "enum_list.variant" to setOf("chips", "radio"),
    "scaffold.sheet_state" to setOf("hidden", "partial", "expanded"),
    "tabs.style" to setOf("primary", "secondary"),
    "tab_item.icon_position" to setOf("above", "leading"),
    "scaffold.floating_toolbar_orientation" to setOf("horizontal", "vertical"),
    "scaffold.floating_toolbar_placement" to setOf("bottom_center", "bottom_start", "bottom_end", "center_start", "center_end"),
    "scaffold.floating_toolbar_exit_direction" to setOf("bottom", "top", "start", "end"),
    "pane_scaffold.variant" to setOf("list_detail", "supporting"),
    "navigation_rail.variant" to setOf("standard", "wide", "modal"),
    "scaffold.drawer_variant" to setOf("modal", "dismissible", "permanent"),
    "scaffold.bottom_bar_behavior" to setOf("pinned", "exit_always"),
    "scaffold.fab_position" to setOf("end", "end_overlay", "center"),
    "button.checked_shape" to setOf("round", "square"),
    "navigation_rail.arrangement" to setOf("top", "center", "bottom"),
    "carousel.strategy" to setOf("multi_browse", "uncontained", "centered_hero"),
    "search_bar.variant" to setOf("full_screen", "docked"),
    "button.shape_role" to setOf("leading", "middle", "trailing", "top", "bottom"),
    "theme.layout_direction" to setOf("ltr", "rtl"),
    "window.size_class" to setOf("compact", "medium", "expanded"),
    "snackbar.result" to setOf("dismissed", "action"),
)

val TEXT_INPUT_CONTRACT = TextInputContract(
    selection = TextInputSelectionContract(
        type = "two-number-array",
        unit = "unicode-scalar",
        minimum = 0L,
        order = "start<=end",
        upperBound = "authored-value",
        lifecycle = "new-presentation-seed",
        whenRetainedDraftWins = "ignore",
    ),
    maxLength = TextInputMaxLengthContract(
        type = "positive-integer",
        unit = "unicode-scalar",
        behavior = "truncate-before-commit",
        authoredValueMustFit = true,
        retainedDraftMustFit = true,
    ),
    transformOrder = listOf("single_line", "filter", "max_length"),
    filterCharacterSets = mapOf("digits" to "ascii-digit", "alnum" to "ascii-alphanumeric"),
    filterUnknown = "none",
    filterAuthoredValueMustMatch = true,
    filterRetainedDraftMustMatch = true,
    mask = TextInputMaskContract(
        slot = "#",
        minimumSlots = 1,
        unit = "unicode-scalar",
        overflow = "unformatted",
        incompatibleWith = setOf("password", "syntax"),
    ),
    contentPadding = TextInputPaddingContract(
        type = "non-negative-dp",
        appliesTo = "all-interior-sides",
    ),
    variantDefault = "outlined",
    variantUnknown = "outlined",
    hideKeyboardOnSubmitRequires = "on_submit",
    errorDescriptionPrecedence = listOf("semantics.error", "supporting_text"),
    logicalValueExcludes = listOf("prefix", "suffix", "mask-literals"),
)

/** SPEC 14.6: node types whose id/value participate in input state. */
val STATEFUL_NODE_TYPES: Set<String> = setOf(
    "text_input", "checkbox", "switch", "enum_list", "slider", "editor",
    "search_bar", "dropdown", "segmented_button", "variant_host",
    // Conditionally stateful: a plain button carries no state and needs no
    // id. SpecValidator's isStateful predicate registers these ONLY when
    // `checked` is present — see the `editor` precedent.
    "button", "icon_button")

val ACTION_HOOK_KEYS: Set<String> = setOf("on_tap", "on_change", "on_submit", "on_save", "on_enter", "on_pick", "on_reorder", "on_refresh", "on_sheet_change", "on_expand_change", "on_long_tap", "on_add_row", "on_add_col", "on_day_tap", "on_month_change", "on_point_tap", "on_trigger", "header_action")

val OFFLINE_POLICIES: Set<String> = setOf("drop", "queue", "wake")
const val OFFLINE_DEFAULT = "drop"

val NODE_SCHEMA: Map<String, NodeRow> = mapOf(
    "text" to NodeRow(setOf("text"), setOf("style", "font_weight", "color", "selectable", "max_lines", "syntax")),
    "rich_text" to NodeRow(setOf("spans"), setOf("style")),
    "icon" to NodeRow(setOf("name"), setOf("size", "color", "badge", "content_description")),
    "image" to NodeRow(setOf("url"), setOf("content_description", "content_scale")),
    "date_stamp" to NodeRow(setOf(), setOf("day", "month", "month_index", "year", "time")),
    "section_header" to NodeRow(setOf("title"), setOf("trailing")),
    "empty_state" to NodeRow(setOf(), setOf("icon", "title", "caption", "action_label", "on_tap")),
    "progress" to NodeRow(setOf(), setOf("variant", "value")),
    "badge" to NodeRow(setOf("label"), setOf("icon", "color", "children")),
    "row" to NodeRow(setOf("children"), setOf("spacing", "align", "arrange", "scroll", "fill", "overlap", "content_padding")),
    "column" to NodeRow(setOf("children"), setOf("spacing", "align", "arrange", "scroll", "fill", "reverse_scroll", "overlap")),
    "flow_row" to NodeRow(setOf("children"), setOf("spacing", "run_spacing", "align", "arrange")),
    "box" to NodeRow(setOf("children"), setOf("alignment", "on_tap", "on_long_tap")),
    "surface" to NodeRow(setOf("children"), setOf("color", "shape", "elevation", "shadow_elevation")),
    "lazy_column" to NodeRow(setOf("children"), setOf("spacing", "content_padding")),
    "variant_host" to NodeRow(setOf("id", "value", "variants"), setOf()),
    "spacer" to NodeRow(setOf(), setOf()),
    "divider" to NodeRow(setOf(), setOf("color", "thickness")),
    "card" to NodeRow(setOf("children"), setOf("on_tap", "on_long_tap", "swipe_start", "swipe_end", "variant")),
    "collapsible" to NodeRow(setOf("id", "header", "children"), setOf("collapsed", "on_long_tap", "swipe_start", "swipe_end")),
    "reorderable_list" to NodeRow(setOf("items"), setOf("on_reorder")),
    "tabs" to NodeRow(setOf("items", "children"), setOf("initial", "scrollable", "pager_only", "on_change", "id", "style", "indicator")),
    "table" to NodeRow(setOf("rows"), setOf("aligns", "on_add_row", "on_add_col")),
    "button" to NodeRow(setOf("label", "on_tap"), setOf("icon", "variant", "enabled", "size", "shape", "animate_shape", "checked", "on_change", "expanded", "checked_shape", "shape_role", "checked_icon", "color")),
    "icon_button" to NodeRow(setOf("icon", "on_tap"), setOf("content_description", "badge", "enabled", "variant", "checked", "on_change", "checked_icon", "size", "shape", "width_mode", "color")),
    "chip" to NodeRow(setOf("label"), setOf("on_tap", "selected", "icon", "enabled", "variant", "trailing_icon", "avatar", "content_spacing")),
    "menu" to NodeRow(setOf(), setOf("items", "groups", "footer", "icon", "enabled", "initial_scroll")),
    "text_input" to NodeRow(setOf("id"), setOf("value", "hint", "label", "on_change", "on_submit", "single_line", "min_lines", "max_lines", "monospace", "syntax", "password", "keyboard", "autofocus", "clear_on_submit", "enabled", "variant", "is_error", "supporting_text", "prefix", "suffix", "leading_icon", "trailing_icon", "max_length", "selection", "hide_keyboard_on_submit", "content_padding", "mask", "filter")),
    "editor" to NodeRow(setOf("id"), setOf("document", "value", "on_save", "on_enter", "single_line", "min_lines", "max_lines", "read_only", "syntax", "line_numbers", "complete", "chromeless", "publish_state", "autofocus", "toolbar", "enabled")),
    "checkbox" to NodeRow(setOf("id"), setOf("checked", "state", "stroke", "label", "on_change", "enabled")),
    "switch" to NodeRow(setOf("id"), setOf("checked", "label", "on_change", "enabled", "thumb_icon")),
    "enum_list" to NodeRow(setOf("id", "options"), setOf("value", "multi_select", "allow_add", "on_change", "enabled", "variant", "children")),
    "date_button" to NodeRow(setOf("label", "on_pick"), setOf("value", "enabled", "mode", "min_date", "max_date", "disabled_weekdays")),
    "time_button" to NodeRow(setOf("label", "on_pick"), setOf("value", "enabled", "display_mode")),
    "slider" to NodeRow(setOf("id", "on_change"), setOf("value", "value_end", "min", "max", "values", "enabled", "track", "orientation", "color", "color_end", "thumb_icon", "value_label", "track_icon_start", "track_icon_end")),
    "chart" to NodeRow(setOf("series"), setOf("kind", "height", "y_range", "summary", "on_point_tap", "children")),
    "canvas" to NodeRow(setOf("width", "height", "ops"), setOf("children")),
    "month_grid" to NodeRow(setOf("month"), setOf("marks", "selected", "min_month", "max_month", "min_date", "max_date", "disabled_weekdays", "range_start", "range_end", "on_day_tap", "on_month_change", "children")),
    "scaffold" to NodeRow(setOf(), setOf("top_bar", "body", "bottom_bar", "fab", "floating_toolbar", "drawer", "snackbar", "snackbar_action", "on_refresh", "top_bar_style", "top_bar_subtitle", "scroll_behavior", "floating_toolbar_orientation", "floating_toolbar_expanded", "floating_toolbar_placement", "floating_toolbar_fab", "floating_toolbar_scroll", "floating_toolbar_exit_direction", "refresh_indicator", "is_refreshing", "snackbar_duration", "snackbar_dismiss", "snackbar_max_lines", "sheet", "sheet_peek_height", "sheet_state", "on_sheet_change", "fab_hide_on_scroll", "drawer_variant", "bottom_bar_behavior", "fab_position", "top_bar_expanded", "top_bar_collapsed_height", "top_bar_expanded_height", "top_bar_centered", "snackbar_content", "rail")),
    "tooltip" to NodeRow(setOf("children", "text"), setOf("position", "caret", "caret_width", "caret_height", "rich", "title", "action_label", "on_action", "shown")),
    "pane_scaffold" to NodeRow(setOf("list", "detail"), setOf("extra", "variant")),
    "navigation_rail" to NodeRow(setOf("items"), setOf("variant", "expanded", "arrangement", "header", "hide_on_collapse", "on_expand_change")),
    "search_bar" to NodeRow(setOf("id"), setOf("value", "hint", "variant", "on_search", "on_change", "leading_icon", "trailing_icon", "children", "enabled")),
    "dropdown" to NodeRow(setOf("id", "options"), setOf("value", "label", "hint", "editable", "on_change", "enabled", "report_caret")),
    "segmented_button" to NodeRow(setOf("id", "options"), setOf("value", "multi_select", "on_change", "enabled")),
    "carousel" to NodeRow(setOf("children"), setOf("strategy", "item_width", "item_spacing", "content_padding", "item_corner")),
    "button_group" to NodeRow(setOf("items"), setOf("overflow_icon")),
    "lazy_grid" to NodeRow(setOf("children"), setOf("columns", "min_item_width", "reverse", "spacing", "content_padding")),
)

val ACTION_SCHEMA: Map<String, ActionRow> = mapOf(
    "remote" to ActionRow(setOf("action"), setOf("args", "when_offline", "dedupe", "ttl_s", "confirm", "capture_fields", "open_surface")),
    "view.switch" to ActionRow(setOf("builtin", "view"), setOf()),
    "variant.switch" to ActionRow(setOf("builtin", "id"), setOf("value")),
    "surface.open" to ActionRow(setOf("builtin", "surface"), setOf()),
    "clipboard.copy" to ActionRow(setOf("builtin", "text"), setOf()),
    "share.send" to ActionRow(setOf("builtin", "text"), setOf("title")),
    "companion.settings.open" to ActionRow(setOf("builtin"), setOf()),
    "trigger.fire" to ActionRow(setOf("builtin", "id"), setOf()),
    "dialog.submit" to ActionRow(setOf("builtin"), setOf("value", "capture_fields")),
    "dialog.dismiss" to ActionRow(setOf("builtin"), setOf()),
)

/** SPEC 4/16-17: each member name's contract value type. LD-10 drives the
 * validator's scalar type-checks off this instead of coercing accessors. */
val FIELD_TYPES: Map<String, String> = mapOf(
    "action_label" to "string",
    "aligns" to "align-array",
    "allow_add" to "boolean",
    "animate_shape" to "boolean",
    "annotation" to "string",
    "arrangement" to "string",
    "autofocus" to "boolean",
    "avatar" to "identifier",
    "badge" to "string-or-number",
    "bg" to "color",
    "body" to "node",
    "bottom_bar" to "node",
    "bottom_bar_behavior" to "string",
    "caption" to "string",
    "caret" to "boolean",
    "caret_height" to "dp",
    "caret_width" to "dp",
    "checked" to "boolean",
    "checked_icon" to "identifier",
    "checked_shape" to "string",
    "children" to "node-array",
    "chromeless" to "boolean",
    "clear_on_submit" to "boolean",
    "clip" to "boolean",
    "close_icon" to "identifier",
    "collapsed" to "boolean",
    "color" to "color",
    "color_end" to "color",
    "columns" to "positive-integer",
    "complete" to "boolean",
    "content" to "node",
    "content_description" to "string",
    "content_padding" to "dp",
    "content_spacing" to "dp",
    "day" to "integer-1-31",
    "detail" to "node",
    "disabled_weekdays" to "weekday-array",
    "display_mode" to "string",
    "document" to "identifier",
    "drawer" to "node",
    "drawer_variant" to "string",
    "editable" to "boolean",
    "elevation" to "dp",
    "enabled" to "boolean",
    "expanded" to "boolean-or-auto",
    "extra" to "node",
    "fab" to "node",
    "fab_hide_on_scroll" to "boolean",
    "fab_position" to "string",
    "fg" to "color",
    "fill" to "varies-per-node",
    "filter" to "string",
    "floating_toolbar" to "node",
    "floating_toolbar_exit_direction" to "string",
    "floating_toolbar_expanded" to "boolean",
    "floating_toolbar_orientation" to "string",
    "floating_toolbar_placement" to "string",
    "floating_toolbar_scroll" to "boolean",
    "font_weight" to "font-weight",
    "footer" to "node",
    "groups" to "menu-group-array",
    "header" to "node",
    "height" to "number",
    "hide_keyboard_on_submit" to "boolean",
    "hide_on_collapse" to "boolean",
    "hint" to "string",
    "icon" to "identifier",
    "icon_position" to "string",
    "id" to "identifier",
    "indicator" to "tab-indicator-object",
    "initial" to "non-negative-integer",
    "initial_scroll" to "string",
    "is_error" to "boolean",
    "is_refreshing" to "boolean",
    "italic" to "boolean",
    "item_corner" to "dp",
    "item_spacing" to "dp",
    "item_width" to "dp",
    "items" to "varies-per-node",
    "key" to "identifier",
    "keyboard" to "enum",
    "label" to "string",
    "leading_icon" to "identifier",
    "line_numbers" to "boolean",
    "list" to "node",
    "marks" to "date-marks-object",
    "mask" to "string",
    "max" to "number",
    "max_date" to "yyyy-mm-dd",
    "max_items" to "positive-integer",
    "max_length" to "positive-integer",
    "max_lines" to "positive-integer",
    "max_month" to "yyyy-mm",
    "min" to "number",
    "min_date" to "yyyy-mm-dd",
    "min_item_width" to "dp",
    "min_lines" to "positive-integer",
    "min_month" to "yyyy-mm",
    "mode" to "string",
    "mono" to "boolean",
    "monospace" to "boolean",
    "month" to "yyyy-mm",
    "month_index" to "integer-1-12",
    "multi_select" to "boolean",
    "name" to "string",
    "ops" to "canvas-op-array",
    "options" to "enum-option-array",
    "orientation" to "string",
    "overflow_icon" to "identifier",
    "overlap" to "dp",
    "padding" to "dp",
    "pager_only" to "boolean",
    "password" to "boolean",
    "position" to "string",
    "prefix" to "string",
    "publish_state" to "boolean",
    "rail" to "node",
    "range_end" to "yyyy-mm-dd",
    "range_start" to "yyyy-mm-dd",
    "read_only" to "boolean",
    "refresh_indicator" to "string",
    "report_caret" to "boolean",
    "reverse" to "boolean",
    "reverse_scroll" to "boolean",
    "rich" to "boolean",
    "rows" to "table-row-array",
    "run_spacing" to "dp",
    "scroll" to "boolean",
    "scroll_behavior" to "string",
    "scroll_here" to "boolean",
    "scrollable" to "boolean",
    "selectable" to "boolean",
    "selected" to "varies-per-node",
    "selection" to "two-number-array",
    "semantics" to "semantics-object",
    "series" to "chart-series-array",
    "shadow_elevation" to "dp",
    "shape_role" to "enum",
    "sheet" to "node",
    "sheet_peek_height" to "dp",
    "sheet_state" to "string",
    "shown" to "boolean",
    "single_line" to "boolean",
    "size" to "varies-per-node",
    "snackbar" to "string",
    "snackbar_action" to "label-on-tap-object",
    "snackbar_content" to "node",
    "snackbar_dismiss" to "boolean",
    "snackbar_duration" to "string",
    "snackbar_max_lines" to "positive-integer",
    "spacing" to "dp",
    "spans" to "rich-span-array",
    "state" to "string",
    "strategy" to "string",
    "stroke" to "stroke-object",
    "suffix" to "string",
    "summary" to "string",
    "supporting_text" to "string",
    "swipe_end" to "swipe-object",
    "swipe_start" to "swipe-object",
    "syntax" to "identifier",
    "text" to "string",
    "thickness" to "dp",
    "thumb_icon" to "identifier",
    "time" to "string",
    "title" to "string",
    "toolbar" to "toolbar-id-or-item-array",
    "tooltip" to "string",
    "top_bar" to "node",
    "top_bar_centered" to "boolean",
    "top_bar_collapsed_height" to "dp",
    "top_bar_expanded" to "node",
    "top_bar_expanded_height" to "dp",
    "top_bar_subtitle" to "string",
    "track" to "string",
    "track_icon_end" to "identifier",
    "track_icon_start" to "identifier",
    "trailing" to "node",
    "trailing_description" to "string",
    "trailing_icon" to "identifier",
    "trailing_label" to "string",
    "underline" to "boolean",
    "url" to "string",
    "value" to "varies-per-node",
    "value_end" to "number",
    "value_label" to "boolean",
    "values" to "number-array",
    "variant" to "string",
    "variants" to "variant-array",
    "width" to "number",
    "width_mode" to "string",
    "y_range" to "two-number-array",
    "year" to "non-negative-integer",
)
